Update android_build.yml

diff --git a/.github/workflows/android_build.yml b/.github/workflows/android_build.yml
--- a/.github/workflows/android_build.yml
+++ b/.github/workflows/android_build.yml
@@ -7,11 +7,10 @@ on:
 
 jobs:
   build:
-    name: Build APK
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Repo
+      - name: Checkout repository
         uses: actions/checkout@v4
 
       - name: Setup Python
@@ -23,15 +22,22 @@ jobs:
         run: |
           sudo apt update
           sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-dev \
-            libxml2-dev libxslt1-dev zlib1g-dev git pkg-config libffi-dev libssl-dev
+            libxml2-dev libxslt1-dev zlib1g-dev git pkg-config libffi-dev libssl-dev curl
+
           pip install --upgrade pip
           pip install cython buildozer
+
+      - name: Accept Android Licenses
+        run: |
+          mkdir -p ~/.android
+          echo '### User Agreements' > ~/.android/repositories.cfg  # prevent SDK errors
+          yes | sdkmanager --licenses || true  # ignore interactive errors
 
       - name: Build APK
         run: |
           buildozer android debug
 
-      - name: Upload APK Artifact
+      - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
           name: kivy-apk
